# Generated by Django 5.1 on 2024-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sub_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
