# Generated by Django 5.1 on 2024-09-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sub_total',
        ),
    ]
