# Generated by Django 5.1 on 2024-10-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзины', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
