# Generated by Django 5.1 on 2024-08-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='photos/product/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='therapyapp.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
    ]
