# Generated by Django 5.1 on 2024-08-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapyapp', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
