# Generated by Django 5.1 on 2024-08-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyapp', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
