# Generated by Django 5.1 on 2024-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyapp', '0007_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('post', models.CharField(max_length=50, verbose_name='Должность')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
            ],
        ),
    ]
