# Generated by Django 5.1 on 2024-08-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyapp', '0008_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='e_mail',
            field=models.CharField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
