# Generated by Django 5.1 on 2024-08-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyapp', '0009_worker_e_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('company_name', models.CharField(max_length=120, verbose_name='Компания')),
                ('e_mail', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('content', models.CharField(verbose_name='Доп информация')),
            ],
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['name'], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
