# Generated by Django 5.1 on 2024-08-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyapp', '0010_cooperationrequest_alter_worker_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название направления')),
                ('content', models.TextField(blank=True, verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, upload_to='photos/direction/%Y/%m/%d', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Направления товаров',
                'verbose_name_plural': 'Направления товаров',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='category',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='therapyapp.direction'),
        ),
        migrations.AddField(
            model_name='product',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='therapyapp.direction'),
        ),
    ]
